### PR TITLE
step-to-obj fixes

### PR DESCRIPTION
**Pull request by g-rauhoeft**
Here's a few fixes I implemented while trying to get step importing to work:

* Git always attempted to add the */target folders to my commits, so I added it to the .gitignore.
* The step-to-obj example outputs a .stp file instead of an .obj. I changed that.
* triangulation.rs panicked when accessing edges on line 99. This was because the to_compressed_shell function writes an index to the boundaries vector that isn't necessarily a valid index for the edge vector. ~I enumerated the edges and added this index instead. I hope this is what was meant to happen in the code. It works for most of my .stp test cases, but I think I'll have to change the .or_else branch as well for it to function fully.~ This was because a new index was being added to the eidx_map even if the function could still return None in a filter_map within to_compressed_shell of Table. I moved adding a new index below all conditions potentially returning None.

Please let me know what you think and if you'd like any changes.

### CODE REVIEW

**Comment by piaoger** [comment]
> Here's a few fixes I implemented while trying to get step importing to work:
> 
>     * Git always attempted to add the */target folders to my commits, so I added it to the .gitignore.
> 
>     * The step-to-obj example outputs a .stp file instead of an .obj. I changed that.
> 
>     * triangulation.rs panicked when accessing edges on line 99. This was because the to_compressed_shell function writes an index to the boundaries vector that isn't necessarily a valid index for the edge vector. I enumerated the edges and added this index instead. I hope this is what was meant to happen in the code. It works for most of my .stp test cases, but I think I'll have to change the .or_else branch as well for it to function fully.
> 
> 
> Please let me know what you think and if you'd like any changes.

I tried your code for a couple of step files, including one generated from sample bottle,  and found the result objs are always empty though no panics an more. 

```text
PolygonMesh { attributes: StandardAttributes { positions: [], uv_coords: [], normals: [] }, faces: Faces { tri_faces: [], quad_faces: [], other_faces: [] } }
```

**Comment by g-rauhoeft** [comment]
Thanks for the feedback @piaoger, I'm on it! :)

**Comment by g-rauhoeft** [comment]
@piaoger the cause of the panic was in a different place than I thought. It should work better now.

**Comment by piaoger** [comment]
> @piaoger the cause of the panic was in a different place than I thought. It should work better now.

Can you load attached step files correctly? It can write some polygon in resultant obj file but still not complete.

**Comment by g-rauhoeft** [comment]
> > @piaoger the cause of the panic was in a different place than I thought. It should work better now.
> 
> Can you load attached step files correctly? It can write some polygon in resultant obj file but still not complete.

No, unfortunately I can't. I believe step importing is still in early stages of development in truck, so this is to be expected. I'll continue working on it.

**Comment by ytanimura** [comment]
Looks good to us. We will update CHANGELOG etc., run CI on our GitLab and then merge this into master. Please wait for a while.

**Comment by ytanimura** [comment]
Thank you for your pull request! Now merged it!

**Pull request merged**
